tunnel: Desarrolloeg
credentials-file: /app/cloudflared/desarrolloeg.json

ingress:
  - hostname: qa.apps.desarrolloeg.com
    service: http://monolito-qa:7001
  - hostname: api-cotizaciones.desarrolloeg.com
    service: http://monolito:7000
  - hostname: apps.desarrolloeg.com
    service: http://monolito:7000
  - hostname: api-constancias.desarrolloeg.com
    service: http://monolito:7000
  - hostname: clubfactura.desarrolloeg.com
    service: http://monolito:7000
  - hostname: sync.desarrolloeg.com
    service: http://desarrolloeg-sync:8787
  - service: http_status:404
